### ISSUE TITLE
TypeError: run() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by vasudev13** [karakatic/EvoPreprocess#1]
When performing feature selection by following approach, I am getting following error. Is it an issues with library version?

`
X_new = EvoFeatureSelection(
    evaluator=DecisionTreeRegressor(max_depth=2),
    optimizer=nia.DifferentialEvolution,
    random_seed=1,
    n_runs=5,
    n_folds=5,
).fit_transform(
                                  X,
                                   Y)
`

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.6/dist-packages/EvoPreprocess/feature_selection/EvoFeatureSelection.py", line 126, in _run
    return evo.run()
TypeError: run() missing 1 required positional argument: 'task'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-32-9dee3dd924b8> in <module>()
----> 1 X_new.fit_transform(X,Y)

4 frames
/usr/local/lib/python3.6/dist-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    554         else:
    555             # fit method of arity 2 (supervised transformation)
--> 556             return self.fit(X, y, **fit_params).transform(X)
    557 
    558 

/usr/local/lib/python3.6/dist-packages/sklearn/feature_selection/univariate_selection.py in fit(self, X, y)
    347 
    348         self._check_params(X, y)
--> 349         score_func_ret = self.score_func(X, y)
    350         if isinstance(score_func_ret, (list, tuple)):
    351             self.scores_, self.pvalues_ = score_func_ret

/usr/local/lib/python3.6/dist-packages/EvoPreprocess/feature_selection/EvoFeatureSelection.py in select(self, X, y)
    114 
    115         with Pool(processes=self.n_jobs) as pool:
--> 116             results = pool.starmap(EvoFeatureSelection._run, evos)
    117 
    118         return EvoFeatureSelection._reduce(results, self.n_runs, self.n_folds, self.benchmark, X.shape[1])

/usr/lib/python3.6/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    272         `func` and (a, b) becomes func(a, b).
    273         '''
--> 274         return self._map_async(func, iterable, starmapstar, chunksize).get()
    275 
    276     def starmap_async(self, func, iterable, chunksize=None, callback=None,

/usr/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

TypeError: run() missing 1 required positional argument: 'task'

<br>
<br>
Thanks in advance.

**Comment by karakatic** [comment]
Thank you for this, I'll let you know when the error is handled.

**Comment by karakatic** [comment]
It seems that it is a version issue. Let me know the versions of your packages.

The working example, based on your code is the following:
```
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from EvoPreprocess.feature_selection import EvoFeatureSelection
import NiaPy.algorithms.basic as nia

if __name__ == '__main__':
    random_seed = 1000
    dataset = load_boston()
    X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target,
                                                        test_size=0.33,
                                                        random_state=random_seed)

    # Your code
    X_new = EvoFeatureSelection(evaluator=DecisionTreeRegressor(max_depth=2),
                                optimizer=nia.DifferentialEvolution,
                                random_seed=1, n_runs=5, n_folds=5, ).fit_transform(X_train, y_train)
    print(X_new.shape)
```

The package versions used in this example:
- Python 3.7
- niapy 2.0.0rc5
- scikit-learn 0.21.2
- imbalanced-learn 0.5.0
- EvoPreprocess 0.2.0
