### ISSUE TITLE
Upgrade to the latest niapy release

### ISSUE THREAD

**Issue by firefly-cpp** [karakatic/EvoPreprocess#8]
niapy interface for the representation of problems has recently undergone to major revision. This is probably the final change
of niapy interface. Please make your package consistent with the latest niapy release (2.0.0rc17).

**Comment by firefly-cpp** [comment]
@zStupan, please check it out.

**Comment by firefly-cpp** [comment]
Any progress in solving this issue?

**Comment by karakatic** [comment]
Thank you for raising the issue. It's solved now.
